// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kvODA5lwW6gZCS6ozjmyPyC2A9wnpLk',
    appId: '1:118197154191:web:39bb0da39fcda416ca9bfa',
    messagingSenderId: '118197154191',
    projectId: 'casal-finance-c3b56',
    authDomain: 'casal-finance-c3b56.firebaseapp.com',
    storageBucket: 'casal-finance-c3b56.firebasestorage.app',
    measurementId: 'G-XWQVKNV0NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl-oDyXyLyZZL94Ow0S8fllKRjNXaheh4',
    appId: '1:118197154191:android:525063b5a4c24745ca9bfa',
    messagingSenderId: '118197154191',
    projectId: 'casal-finance-c3b56',
    storageBucket: 'casal-finance-c3b56.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADqrVZ_YPBteTgg-g1__wKrWiMxkfchtc',
    appId: '1:118197154191:ios:ea39e0d7404fdcceca9bfa',
    messagingSenderId: '118197154191',
    projectId: 'casal-finance-c3b56',
    storageBucket: 'casal-finance-c3b56.firebasestorage.app',
    androidClientId: '118197154191-36bprdpsesmbf4rqhlktrqrjcctl72d8.apps.googleusercontent.com',
    iosClientId: '118197154191-mqhq73e1cd8g839gmktdpi9cfpjl5t3u.apps.googleusercontent.com',
    iosBundleId: 'com.matiasdevts.casalfinance',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADqrVZ_YPBteTgg-g1__wKrWiMxkfchtc',
    appId: '1:118197154191:ios:9bbb810b200a5525ca9bfa',
    messagingSenderId: '118197154191',
    projectId: 'casal-finance-c3b56',
    storageBucket: 'casal-finance-c3b56.firebasestorage.app',
    androidClientId: '118197154191-36bprdpsesmbf4rqhlktrqrjcctl72d8.apps.googleusercontent.com',
    iosClientId: '118197154191-eqqag7kctn291t381a2tsqiluvorefak.apps.googleusercontent.com',
    iosBundleId: 'com.example.casalFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0kvODA5lwW6gZCS6ozjmyPyC2A9wnpLk',
    appId: '1:118197154191:web:20986db7307654daca9bfa',
    messagingSenderId: '118197154191',
    projectId: 'casal-finance-c3b56',
    authDomain: 'casal-finance-c3b56.firebaseapp.com',
    storageBucket: 'casal-finance-c3b56.firebasestorage.app',
    measurementId: 'G-EYK53QET56',
  );
}
